#!/usr/bin/env python

import resource_to_cpp

Import("env")
Import("env_modules")

env_oidn = env_modules.Clone()

# Thirdparty source files

thirdparty_obj = []

thirdparty_dir = "#thirdparty/oidn/"
thirdparty_sources = [
    "common/common.cpp",
    "common/half.cpp",
    "common/oidn_utils.cpp",
    "common/platform.cpp",
    "core/arena.cpp",
    "core/arena_planner.cpp",
    "core/buffer.cpp",
    "core/color.cpp",
    "core/concat_conv_chw.cpp",
    "core/concat_conv.cpp",
    "core/concat_conv_hwc.cpp",
    "core/context.cpp",
    "core/conv.cpp",
    "core/device.cpp",
    "core/engine.cpp",
    "core/exception.cpp",
    "core/filter.cpp",
    "core/graph.cpp",
    "core/heap.cpp",
    "core/image.cpp",
    "core/input_process.cpp",
    "core/module.cpp",
    "core/output_process.cpp",
    "core/pool.cpp",
    "core/progress.cpp",
    "core/rt_filter.cpp",
    "core/rtlightmap_filter.cpp",
    "core/subdevice.cpp",
    "core/tensor.cpp",
    "core/tensor_reorder.cpp",
    "core/thread.cpp",
    "core/tza.cpp",
    "core/unet_filter.cpp",
    "core/upsample.cpp",
]
thirdparty_sources = [thirdparty_dir + file for file in thirdparty_sources]

thirdparty_include_dirs = [
    "",
]
thirdparty_include_dirs = [thirdparty_dir + file for file in thirdparty_include_dirs]


env_oidn.Prepend(CPPPATH=thirdparty_include_dirs)
env_oidn.Append(
    CPPDEFINES=[
        "MKLDNN_THR=MKLDNN_THR_SEQ",
        "OIDN_STATIC_LIB",
        "__STDC_CONSTANT_MACROS",
        "__STDC_LIMIT_MACROS",
        "DISABLE_VERBOSE",
        "MKLDNN_ENABLE_CONCURRENT_EXEC",
        "NDEBUG",
    ]
)

env_thirdparty = env_oidn.Clone()
env_thirdparty.disable_warnings()
env_thirdparty.add_source_files(thirdparty_obj, thirdparty_sources)
env.modules_sources += thirdparty_obj

if env["platform"] == "windows" and not env.msvc:
    env_thirdparty.Append(CPPFLAGS=["-mstackrealign"])

weights_in_path = thirdparty_dir + "weights/rtlightmap_hdr.tza"
weights_out_path = thirdparty_dir + "weights/rtlightmap_hdr.gen.cpp"

env_thirdparty.Depends(weights_out_path, weights_in_path)
env_thirdparty.CommandNoCache(
    weights_out_path, weights_in_path, resource_to_cpp.tza_to_cpp
)

# Godot source files

module_obj = []

env_oidn.add_source_files(module_obj, "denoise_wrapper.cpp")
env_modules.add_source_files(
    module_obj, ["register_types.cpp", "lightmap_denoiser.cpp"]
)
env.modules_sources += module_obj

# Needed to force rebuilding the module files when the thirdparty library is updated.
env.Depends(module_obj, thirdparty_obj)
