#!/usr/bin/env python

Import("environment")

import os

import modules_builders

env_modules = environment.Clone()

Export("env_modules")

environment.Depends("modules_enabled.gen.h", Value(environment.modules_path))
environment.CommandNoCache(
    "modules_enabled.gen.h",
    Value(environment.modules_path),
    modules_builders.generate_modules_enabled,
)

environment.modules_sources = []
environment_modules.add_source_files(environment.modules_sources, "register_module_types.gen.cpp")

for module_name, path in environment.modules_path.items():
    if not os.path.isabs(path):
        SConscript(module_name + "/SCsub")  # Built-in.
    else:
        SConscript(path + "/SCsub")  # Custom.

if environment["split_libmodules"]:
    environment.split_lib("modules", env_lib=env_modules)
else:
    lib = env_modules.add_library("modules", environment.modules_sources)

    environment.Prepend(LIBS=[lib])
