#!/usr/bin/env python

Import("environment")

environment.servers_sources = []
environment.add_source_files(environment.servers_sources, "*.cpp")

SConscript("arvr/SCsub")
SConscript("camera/SCsub")
SConscript("physics/SCsub")
SConscript("physics_2d/SCsub")
SConscript("visual/SCsub")
SConscript("audio/SCsub")

lib = environment.add_library("servers", environment.servers_sources)

environment.Prepend(LIBS=[lib])
