#!/usr/bin/env python

Import("environment")

environment.drivers_sources = []

# OS drivers
SConscript("network/SCsub")
SConscript("unix/SCsub")

# Sounds drivers
SConscript("alsa/SCsub")
SConscript("coreaudio/SCsub")
SConscript("pulseaudio/SCsub")
if environment["xaudio2"]:
    SConscript("xaudio2/SCsub")

# Midi drivers
SConscript("alsamidi/SCsub")
SConscript("coremidi/SCsub")
SConscript("winmidi/SCsub")

# Graphics drivers
if environment["platform"] != "server":
    SConscript("gles3/SCsub")
    SConscript("gles2/SCsub")
    SConscript("gles_common/SCsub")
    SConscript("gl_context/SCsub")
else:
    SConscript("dummy/SCsub")

# Core dependencies
SConscript("png/SCsub")

environment.add_source_files(environment.drivers_sources, "*.cpp")

lib = environment.add_library("drivers", environment.drivers_sources)
environment.Prepend(LIBS=[lib])
