#!/usr/bin/env python

Import("environment")

environment.scene_sources = []

# Rebel source files
environment.add_source_files(environment.scene_sources, "*.cpp")

# Chain load SCsubs
SConscript("main/SCsub")
SConscript("gui/SCsub")
SConscript("3d/SCsub")
SConscript("2d/SCsub")
SConscript("animation/SCsub")
SConscript("audio/SCsub")
SConscript("resources/SCsub")
SConscript("debugger/SCsub")

# Build it all as a library
lib = environment.add_library("scene", environment.scene_sources)
environment.Prepend(LIBS=[lib])
