#!/usr/bin/env python

Import("environment")

if environment["tools"]:
    environment.projects_manager_sources = []
    environment.add_source_files(environment.projects_manager_sources, "*.cpp")

    lib = environment.add_library("projects-manager", environment.projects_manager_sources)
    environment.Prepend(LIBS=[lib])
