name: 🍎 macOS Builds
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-windows:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: macOS Editor
            os: macos-latest
            artifact: macos-editor
            build-options: dev=yes target=release_debug
            rebel-executable: rebel.osx.opt.tools.64

          - name: macOS Template
            os: macos-latest
            artifact: macos-template
            build-options: dev=yes tools=no target=release
            rebel-executable: rebel.osx.opt.64

    steps:
      - name: Build Rebel
        uses: madmiraal/RebelBuildAction@v3
        with:
          artifact: ${{ matrix.artifact }}
          build-options: ${{ matrix.build-options }}
          rebel-executable: ${{ matrix.rebel-executable }}
