name: 🏁 Windows Builds
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-windows:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows Editor
            os: windows-latest
            artifact: windows-editor
            build-options: dev=yes target=release_debug
            rebel-executable: rebel.windows.opt.tools.64.msvc.exe

          - name: Windows Template
            os: windows-latest
            artifact: windows-template
            build-options: dev=yes tools=no target=release
            rebel-executable: rebel.windows.opt.64.msvc.exe

    steps:
      - name: Build Rebel
        uses: madmiraal/RebelBuildAction@v3
        with:
          artifact: ${{ matrix.artifact }}
          build-options: ${{ matrix.build-options }}
          rebel-executable: ${{ matrix.rebel-executable }}
